### ISSUE TITLE
补充与勘误部分题目

### ISSUE THREAD

**Issue by Liu-Steve** [lz61/Fudan-Freshman-Test-2024#2]
“______、服务、牺牲”的复旦精神由老校长李登辉提出。1947年7月5日，李登辉校长在登辉堂对复旦学子进行最后一次演讲。其中一段是“你们现在穿的是学士制服，你们穿过了以后，应当是一个有学问的人，应当从此对国家有所贡献，一个大学毕业生，应当为社会服务，为人类牺牲，服务、牺牲、______，是复旦的精神，更是你们的责任。”

✔团结
奋发
文明

学位论文盲审中仅1份评阅书存在异议时，且其余评阅结论均为“优”时，申请人可提出申诉；否则不得提出申诉，须根据评阅意见对学位论文进行修改后方可提交原异议专家复审，修改时间不少于______个月。
答案选项组

1个月
6个月
12个月
✔3个月

学位论文盲审中有2份评阅书均存在异议时,申请人不得提出申诉，须根据评阅意见对学位论文进行不少于______个月的修改，方可提交原异议专家复审。

✔C.6个月
D.12个月
B.3个月
A.1个月

复旦大学的校名出自______中的“卿云烂兮，纠缦缦兮；日月光华，旦复旦兮”，本义是追求光明，含有自主办学、复兴中华的意味。
答案选项组

《诗经》
《尚书》
《春秋》
✔《尚书大传》

以下关于选课的表述，正确的是：______（多选）

✔第3周起，选课系统关闭，研究生不得再选课、退课，学校根据学籍注册名单确定最终选课名单
✔研究生对于在选课系统内选过的课程，试听后觉得不合适，可以退课，退课时必须完成选课系统内的退课操作
✔研究生参加补修课程学习并通过考核后，可获得相应学分，但所获学分不得计入培养方案要求的学分数
✔研究生网上选课一般安排在每学期第0-2周。其中，第0周为选课时段；第1-2周为试听和调整选课时段，未参加试听的课程不得选课
✔跨学科入学、以同等学力入学、或入学后导师认为有必要补充某些专业基础知识的研究生，须补修课程

研究生因下列哪些情况，不能按时参加课程考试的，可在课程考试前申请缓考：______（多选）

✔患重病或意外伤残
✔课程考试时间冲突
在外实习
家里有事

《上海市生活垃圾管理条例》从______起正式实施？

2019年5月6日
✔2019年7月1日
2020年7月1日
2020年8月1日

白色污染是指？

一种白色化学气体造成的污染
✔塑料废弃物造成的污染
所有白颜色的垃圾造成的污染
白颜色塑料废弃物造成的污染

根据《上海市生活垃圾分类投放指引》，家庭盆栽废弃的树叶属于什么垃圾？

有害垃圾
✔湿垃圾
干垃圾
可回收物

邮箱中或邮件所附链接中要求填写账号密码时该怎么办？

✔甄别发件人，拉黑该邮件并上报信息办
直接进行填写
点进去看看

任何机构和组织一般不会用（hotmail、gmail、163、aol、yahoo）.com等常用个人邮件系统的账号作为服务邮箱。

✔正确
错误

在邮件正文中要求密码、在超链接中要求输入账号密码的行为，大都是钓鱼行为。

错误
✔正确

院系领导或导师给你发邮件要求全班通讯录时，怎么办？

发送班级通讯录
直接发送全部通讯录
选几个发送敷衍一下
✔检查发件人邮箱并通过电话、微信等其他途径联系发件人确认

由他人代写论文，代他人写论文，或者买卖论文的行为将给予哪一类处分：

记过处分
✔开除学籍处分
留校察看以上处分

根据《复旦大学学生纪律处分条例》，对于以下哪些违反学术规范的行为，将给予记过处分：

✔故意一稿多投、重复发表的
✔在申请课题、学位等过程中提供虚假学术信息的
✔未参加研究、创作，在研究生成果、作品上署名，未经过他人许可不当使用他人署名，虚构合作者共同署名，或者多人共同完成研究、创作，在发表研究成果、作品时未注明他人工作、贡献的
✔抄袭他人作品或者剽窃、侵占他人研究成果的

「勘误」

学校不予注册的情形包括：______（多选）

✔保留入学资格 
✔保留学籍（休学、服兵役、联合培养） 
✔无正当理由欠缴学费 
✔学习年限届满 
✔未通过入学教育测试 

根据《上海市生活垃圾分类投放指引》，小孩用过的是尿片应投入？

蓝色垃圾桶
红色垃圾桶
✔黑色垃圾桶
棕色垃圾桶

**Comment by lz61** [comment]
感谢!
